import { VizConfigSegments } from "./types";
import { getQuestionKey } from "../utils";

export function validateConfig(vizConfigSegments: VizConfigSegments) {
  if (!vizConfigSegments) {
    throw new Error("vizConfigSegments is required");
  }

  // There is at least one responseQuestion
  if (
    !Array.isArray(vizConfigSegments.responseQuestions) ||
    vizConfigSegments.responseQuestions.length === 0
  ) {
    throw new Error("vizConfigSegments must include at least one responseQuestion");
  }

  // There are no duplicate responseQuestions
  {
    const seen = new Set<string>();
    for (const rq of vizConfigSegments.responseQuestions) {
      const key = getQuestionKey(rq);
      if (seen.has(key)) {
        throw new Error(`duplicate responseQuestion detected: ${key}`);
      }
      seen.add(key);
    }
  }


  // groupingQuestions.x and groupingQuestions.y are disjoint (measured by questionKey generated by getQuestionKey from utils.ts in this package)
  const x = vizConfigSegments.groupingQuestions?.x ?? [];
  const y = vizConfigSegments.groupingQuestions?.y ?? [];

  const xKeys = new Set(x.map(getQuestionKey));
  for (const q of y) {
    const key = getQuestionKey(q);
    if (xKeys.has(key)) {
      throw new Error(
        `groupingQuestions.x and groupingQuestions.y must be disjoint — question ${key} appears in both`
      );
    }
  }

  // if syntheticSampleSize is defined, it is a strictly positive number
  if (
    vizConfigSegments.syntheticSampleSize !== undefined &&
    (typeof vizConfigSegments.syntheticSampleSize !== "number" ||
      !(vizConfigSegments.syntheticSampleSize > 0))
  ) {
    throw new Error("syntheticSampleSize must be a strictly positive number if defined");
  }

  // each length is strictly positive
  const lengths: Array<[string, number]> = [
    ["minGroupAvailableWidth", vizConfigSegments.minGroupAvailableWidth],
    ["minGroupHeight", vizConfigSegments.minGroupHeight],
    ["groupGapX", vizConfigSegments.groupGapX],
    ["groupGapY", vizConfigSegments.groupGapY],
    ["responseGap", vizConfigSegments.responseGap],
  ];

  for (const [name, value] of lengths) {
    if (typeof value !== "number" || !(value > 0)) {
      throw new Error(`${name} must be a strictly positive number`);
    }
  }
}